services:

  activemq:
    image: rmohr/activemq:latest
    container_name: starlink-broker
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - starlink-network

  event-store-builder:
    build:
      context: .
      dockerfile: event-store-builder/Dockerfile
    container_name: starlink-event-store
    volumes:
      - ./event-store-builder/eventstore:/app/eventstore
    environment:
      - ACTIVEMQ_URL=tcp://activemq:61616
    depends_on:
      - activemq
    networks:
      - starlink-network

  rain-fade-monitor:
    build:
      context: .
      dockerfile: rain-fade-monitor/Dockerfile
    container_name: starlink-monitor-service
    volumes:
      - ./event-store-builder/eventstore:/app/eventstore
      - ./datamart.db:/app/datamart.db
    environment:
      - ACTIVEMQ_URL=tcp://activemq:61616
    ports:
      - "7000:7000"
    depends_on:
      - activemq
    networks:
      - starlink-network

  weather-extractor:
    build:
      context: .
      dockerfile: weather-extractor/Dockerfile
    container_name: starlink-weather-extractor
    environment:
      - ACTIVEMQ_URL=tcp://activemq:61616
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    depends_on:
      - activemq
    networks:
      - starlink-network

  spacex-extractor:
    build:
      context: .
      dockerfile: spacex-extractor/Dockerfile
    container_name: starlink-spacex-extractor
    environment:
      - ACTIVEMQ_URL=tcp://activemq:61616
    depends_on:
      - activemq
    networks:
      - starlink-network

  prometheus:
    image: prom/prometheus:latest
    container_name: starlink-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - starlink-network

  grafana:
    image: grafana/grafana:latest
    container_name: starlink-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - starlink-network

networks:
  starlink-network:
    driver: bridge
