  services:

    activemq:
      image: rmohr/activemq:latest
      container_name: starlink-broker

      ports:
        - "61616:61616"
        - "8161:8161"

      networks:
        - starlink-network

    event-store-builder:
      image: maven:3.9.6-eclipse-temurin-21
      container_name: starlink-event-store

      working_dir: /app/event-store-builder

      volumes:
        - .:/app

      environment:
        - ACTIVEMQ_URL=tcp://activemq:61616

      command: >
        mvn compile exec:java
        -Dexec.mainClass="org.ulpgc.starlink.eventstore.Main"

      depends_on:
        - activemq

      networks:
        - starlink-network

    rain-fade-monitor:
      image: maven:3.9.6-eclipse-temurin-21
      container_name: starlink-monitor-service

      working_dir: /app/rain-fade-monitor

      volumes:
        - .:/app

      environment:
        - ACTIVEMQ_URL=tcp://activemq:61616

      command: >
            mvn compile exec:java
            -Dexec.mainClass="org.ulpgc.starlink.monitor.Main"
            -Dexec.args="/app/event-store-builder/eventstore /app/datamart.db"

      ports:
        - "7000:7000"

      depends_on:
        - activemq

      networks:
        - starlink-network

    weather-extractor:
      image: maven:3.9.6-eclipse-temurin-21
      container_name: starlink-weather-extractor

      working_dir: /app/weather-extractor

      volumes:
        - .:/app

      environment:
        - ACTIVEMQ_URL=tcp://activemq:61616
        - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}

      command: >
        mvn compile exec:java
        -Dexec.mainClass="org.ulpgc.starlink.weather.Main"

      depends_on:
        - activemq

      networks:
        - starlink-network

    spacex-extractor:
      image: maven:3.9.6-eclipse-temurin-21
      container_name: starlink-spacex-extractor

      working_dir: /app/spacex-extractor

      volumes:
        - .:/app

      environment:
        - ACTIVEMQ_URL=tcp://activemq:61616

      command: >
        mvn compile exec:java
        -Dexec.mainClass="org.ulpgc.starlink.spacex.Main"

      depends_on:
        - activemq

      networks:
        - starlink-network

  networks:

    starlink-network:
      driver: bridge

